# Site settings
title:          Golem
description:    "Every alchemist needs a golem."
baseurl:        "/golem"
url:            "https://openalchem.ist"
newsurl:        "https://openalchem.ist/news"

# Author
author:
  name:         Alexander Wellbrock
  url:          https://openalchem.ist
  email:        a.wellbrock@mailbox.org

# Build settings
markdown:       kramdown
include:
  - _pages
highlighter:    rouge

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /essays/:title
paginate:       7

# Excludes
exclude: [ Gemfile, Gemfile.lock, golem.gemspec, project-icon.png ]
